import numpy as np
A =np.arange(6,16,1)
B = np.arange(1,20,2)
print("Array A elements :\n",A)
print("Array B elements:\n",B)
print("maximum elements from both:",np.maximum(A,B))
print("\n minimum element from both:",np.minimum(A,B))
print("\n multiply element from both:",np.multiply(A,B))
print("\npower element from both:",np.power(A,B))
print("\n mod element from both:",np.mod(A,B))
a = np.arange(6,-6,-1)
b = np.arange(6,-18,-2)
print("\ncopysign element from both:",np.copysign(a,b))
print("\ncopy sign from both",np.copysign(b,a))