import turtle as t
a = t.Turtle()
print(a.shape())
print(a.shape("turtle"))
print(a.forward(100))
print(a.color("blue"))
print(a.forward(100))
print(a.color("red","blue"))
print(a.backward(300))
t.colormode(255)
print(a.color(120,40,50))
wn = t.Screen()
print(wn.bgcolor("green"))
print(wn.title("alka"))
